// This file is auto-generated by @hey-api/openapi-ts

export { type Options, postHitokoto } from './sdk.gen.js';
export type { AtelinoInternalDtoCreateHitokotoRequest, AtelinoInternalDtoHitokotoIdRequest, AtelinoInternalDtoResponse, ClientOptions, PostHitokotoData, PostHitokotoError, PostHitokotoErrors, PostHitokotoResponse, PostHitokotoResponses } from './types.gen.js';
