// This file is auto-generated by @hey-api/openapi-ts

export { deleteHitokotoById, type Options, postHitokoto } from './sdk.gen.js';
export type { AtelinoInternalDtoCreateHitokotoRequest, AtelinoInternalDtoHitokotoIdRequest, AtelinoInternalDtoResponse, ClientOptions, DeleteHitokotoByIdData, DeleteHitokotoByIdError, DeleteHitokotoByIdErrors, DeleteHitokotoByIdResponse, DeleteHitokotoByIdResponses, PostHitokotoData, PostHitokotoError, PostHitokotoErrors, PostHitokotoResponse, PostHitokotoResponses } from './types.gen.js';
