// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { CreateHitokotoData, CreateHitokotoErrors, CreateHitokotoResponses, DeleteHitokotoByIdData, DeleteHitokotoByIdErrors, DeleteHitokotoByIdResponses, GetHitokotoByIdData, GetHitokotoByIdErrors, GetHitokotoByIdResponses, GetHitokotoListData, GetHitokotoListErrors, GetHitokotoListResponses, GetHitokotoRandomData, GetHitokotoRandomErrors, GetHitokotoRandomResponses, GetUserByIdData, GetUserByIdErrors, GetUserByIdResponses, GetUserListData, GetUserListErrors, GetUserListResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutErrors, LogoutResponses, RefreshTokenData, RefreshTokenErrors, RefreshTokenResponses, RegisterData, RegisterErrors, RegisterResponses, SendVerificationCodeData, SendVerificationCodeErrors, SendVerificationCodeResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 随机获取一言
 *
 * 从数据库中随机获取一条一言记录。
 */
export const getHitokotoRandom = <ThrowOnError extends boolean = false>(options?: Options<GetHitokotoRandomData, ThrowOnError>) => (options?.client ?? client).get<GetHitokotoRandomResponses, GetHitokotoRandomErrors, ThrowOnError>({ url: '/api/hitokoto', ...options });

/**
 * 添加一言
 *
 * 创建一条新的一言记录。
 */
export const createHitokoto = <ThrowOnError extends boolean = false>(options: Options<CreateHitokotoData, ThrowOnError>) => (options.client ?? client).post<CreateHitokotoResponses, CreateHitokotoErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/hitokoto',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取一言列表
 *
 * 从数据库中查询所有的一言记录。
 */
export const getHitokotoList = <ThrowOnError extends boolean = false>(options?: Options<GetHitokotoListData, ThrowOnError>) => (options?.client ?? client).get<GetHitokotoListResponses, GetHitokotoListErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/hitokoto/list',
    ...options
});

/**
 * 删除一言
 *
 * 传入一言的 ID，从数据库中删除对应的记录。
 */
export const deleteHitokotoById = <ThrowOnError extends boolean = false>(options: Options<DeleteHitokotoByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteHitokotoByIdResponses, DeleteHitokotoByIdErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/hitokoto/{id}',
    ...options
});

/**
 * 获取一言
 *
 * 传入一言的 ID，从数据库中查询对应的记录。
 */
export const getHitokotoById = <ThrowOnError extends boolean = false>(options: Options<GetHitokotoByIdData, ThrowOnError>) => (options.client ?? client).get<GetHitokotoByIdResponses, GetHitokotoByIdErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/hitokoto/{id}',
    ...options
});

/**
 * 获取用户列表
 *
 * 分页获取所有用户的列表。
 */
export const getUserList = <ThrowOnError extends boolean = false>(options?: Options<GetUserListData, ThrowOnError>) => (options?.client ?? client).get<GetUserListResponses, GetUserListErrors, ThrowOnError>({ url: '/api/user/list', ...options });

/**
 * 获取用户
 *
 * 传入用户的 ID，从数据库中查询指定的用户。
 */
export const getUserById = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdData, ThrowOnError>) => (options.client ?? client).get<GetUserByIdResponses, GetUserByIdErrors, ThrowOnError>({ url: '/api/user/{id}', ...options });

/**
 * 用户登录
 *
 * 用户登录接口
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 用户登出
 *
 * 用户登出接口，清除用户的会话信息。
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/auth/logout',
    ...options
});

/**
 * 刷新令牌
 *
 * 使用刷新令牌获取新的访问令牌。
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options: Options<RefreshTokenData, ThrowOnError>) => (options.client ?? client).post<RefreshTokenResponses, RefreshTokenErrors, ThrowOnError>({
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 用户注册
 *
 * 用户注册接口
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 发送验证码
 *
 * 向指定的邮箱发送验证码用于注册或其他用途。
 */
export const sendVerificationCode = <ThrowOnError extends boolean = false>(options: Options<SendVerificationCodeData, ThrowOnError>) => (options.client ?? client).post<SendVerificationCodeResponses, SendVerificationCodeErrors, ThrowOnError>({
    url: '/verify/send',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
