// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:8080/' | (string & {});
};

export type AtelinoInternalDtoCreateHitokotoRequest = {
    content: string;
};

export type AtelinoInternalDtoHitokotoResponse = {
    content?: string;
    created_at?: string;
    id?: number;
};

export type AtelinoInternalDtoLoginRequest = {
    email: string;
    password: string;
};

export type AtelinoInternalDtoRegisterRequest = {
    code: string;
    email: string;
    password: string;
    username: string;
};

export type AtelinoInternalDtoResponse = {
    code?: number;
    data?: unknown;
    message?: string;
};

export type AtelinoInternalDtoTokenResponse = {
    access_token?: string;
    refresh_token?: string;
};

export type AtelinoInternalDtoUserResponse = {
    created_at?: string;
    email?: string;
    id?: number;
    role?: string;
    username?: string;
};

export type GetApiHitokotoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/hitokoto';
};

export type GetApiHitokotoErrors = {
    /**
     * 没有找到对应的一言
     */
    404: AtelinoInternalDtoResponse;
    /**
     * 数据库错误
     */
    500: AtelinoInternalDtoResponse;
};

export type GetApiHitokotoError = GetApiHitokotoErrors[keyof GetApiHitokotoErrors];

export type GetApiHitokotoResponses = {
    /**
     * 请求成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: AtelinoInternalDtoHitokotoResponse;
    };
};

export type GetApiHitokotoResponse = GetApiHitokotoResponses[keyof GetApiHitokotoResponses];

export type PostApiHitokotoData = {
    /**
     * 一言内容
     */
    body: AtelinoInternalDtoCreateHitokotoRequest;
    path?: never;
    query?: never;
    url: '/api/hitokoto';
};

export type PostApiHitokotoErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 该一言已存在
     */
    409: AtelinoInternalDtoResponse;
    /**
     * 数据库错误
     */
    500: AtelinoInternalDtoResponse;
};

export type PostApiHitokotoError = PostApiHitokotoErrors[keyof PostApiHitokotoErrors];

export type PostApiHitokotoResponses = {
    /**
     * 添加成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: AtelinoInternalDtoHitokotoResponse;
    };
};

export type PostApiHitokotoResponse = PostApiHitokotoResponses[keyof PostApiHitokotoResponses];

export type GetApiHitokotoListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页数
         */
        page?: number;
    };
    url: '/api/hitokoto/list';
};

export type GetApiHitokotoListErrors = {
    /**
     * 未授权
     */
    401: AtelinoInternalDtoResponse;
    /**
     * 数据库错误
     */
    500: AtelinoInternalDtoResponse;
};

export type GetApiHitokotoListError = GetApiHitokotoListErrors[keyof GetApiHitokotoListErrors];

export type GetApiHitokotoListResponses = {
    /**
     * 请求成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: Array<AtelinoInternalDtoHitokotoResponse>;
    };
};

export type GetApiHitokotoListResponse = GetApiHitokotoListResponses[keyof GetApiHitokotoListResponses];

export type DeleteApiHitokotoByIdData = {
    body?: never;
    path: {
        /**
         * 一言 ID
         */
        id: number;
    };
    query?: never;
    url: '/api/hitokoto/{id}';
};

export type DeleteApiHitokotoByIdErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 未授权
     */
    401: AtelinoInternalDtoResponse;
    /**
     * 没有找到对应的一言
     */
    404: AtelinoInternalDtoResponse;
    /**
     * 数据库错误
     */
    500: AtelinoInternalDtoResponse;
};

export type DeleteApiHitokotoByIdError = DeleteApiHitokotoByIdErrors[keyof DeleteApiHitokotoByIdErrors];

export type DeleteApiHitokotoByIdResponses = {
    /**
     * 删除成功
     */
    200: AtelinoInternalDtoResponse;
};

export type DeleteApiHitokotoByIdResponse = DeleteApiHitokotoByIdResponses[keyof DeleteApiHitokotoByIdResponses];

export type GetApiHitokotoByIdData = {
    body?: never;
    path: {
        /**
         * 一言 ID
         */
        id: number;
    };
    query?: never;
    url: '/api/hitokoto/{id}';
};

export type GetApiHitokotoByIdErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 未授权
     */
    401: AtelinoInternalDtoResponse;
    /**
     * 没有找到对应的一言
     */
    404: AtelinoInternalDtoResponse;
    /**
     * 数据库错误
     */
    500: AtelinoInternalDtoResponse;
};

export type GetApiHitokotoByIdError = GetApiHitokotoByIdErrors[keyof GetApiHitokotoByIdErrors];

export type GetApiHitokotoByIdResponses = {
    /**
     * 请求成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: AtelinoInternalDtoHitokotoResponse;
    };
};

export type GetApiHitokotoByIdResponse = GetApiHitokotoByIdResponses[keyof GetApiHitokotoByIdResponses];

export type GetApiUserByIdData = {
    body?: never;
    path: {
        /**
         * 用户 ID
         */
        id: number;
    };
    query?: never;
    url: '/api/user/{id}';
};

export type GetApiUserByIdErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 未授权
     */
    401: AtelinoInternalDtoResponse;
    /**
     * 查询失败
     */
    500: AtelinoInternalDtoResponse;
};

export type GetApiUserByIdError = GetApiUserByIdErrors[keyof GetApiUserByIdErrors];

export type GetApiUserByIdResponses = {
    /**
     * 请求成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: AtelinoInternalDtoUserResponse;
    };
};

export type GetApiUserByIdResponse = GetApiUserByIdResponses[keyof GetApiUserByIdResponses];

export type PostAuthLoginData = {
    /**
     * 登录请求体
     */
    body: AtelinoInternalDtoLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 用户名或密码错误
     */
    401: AtelinoInternalDtoResponse;
    /**
     * 登录失败
     */
    500: AtelinoInternalDtoResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * 登录成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: AtelinoInternalDtoTokenResponse;
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRegisterData = {
    /**
     * 注册请求体
     */
    body: AtelinoInternalDtoRegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 该邮箱已注册
     */
    409: AtelinoInternalDtoResponse;
    /**
     * 注册失败
     */
    500: AtelinoInternalDtoResponse;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * 注册成功
     */
    200: AtelinoInternalDtoResponse;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];
