// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:8080/api/' | (string & {});
};

export type AtelinoInternalDtoCreateHitokotoRequest = {
    content: string;
};

export type AtelinoInternalDtoHitokotoIdRequest = {
    id: number;
};

export type AtelinoInternalDtoResponse = {
    code?: number;
    data?: unknown;
    message?: string;
};

export type PostHitokotoData = {
    /**
     * 一言内容
     */
    body: AtelinoInternalDtoCreateHitokotoRequest;
    path?: never;
    query?: never;
    url: '/hitokoto';
};

export type PostHitokotoErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 该一言已存在
     */
    409: AtelinoInternalDtoResponse;
    /**
     * 数据库错误
     */
    500: AtelinoInternalDtoResponse;
};

export type PostHitokotoError = PostHitokotoErrors[keyof PostHitokotoErrors];

export type PostHitokotoResponses = {
    /**
     * 添加成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: AtelinoInternalDtoHitokotoIdRequest;
    };
};

export type PostHitokotoResponse = PostHitokotoResponses[keyof PostHitokotoResponses];
