// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/' | 'https://localhost:8080/' | (string & {});
};

export type AtelinoInternalDtoCreateHitokotoRequest = {
    content: string;
};

export type AtelinoInternalDtoHitokotoResponse = {
    content?: string;
    created_at?: string;
    id?: number;
};

export type AtelinoInternalDtoLoginRequest = {
    email: string;
    password: string;
};

export type AtelinoInternalDtoRefreshTokenRequest = {
    refresh_token: string;
};

export type AtelinoInternalDtoRegisterRequest = {
    code: string;
    email: string;
    password: string;
    username: string;
};

export type AtelinoInternalDtoResponse = {
    code?: number;
    data?: unknown;
    message?: string;
};

export type AtelinoInternalDtoSendVerificationCodeRequest = {
    to: string;
};

export type AtelinoInternalDtoTokenResponse = {
    access_token?: string;
    refresh_token?: string;
};

export type AtelinoInternalDtoUserResponse = {
    created_at?: string;
    email?: string;
    id?: number;
    role?: string;
    username?: string;
};

export type GetHitokotoRandomData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/hitokoto';
};

export type GetHitokotoRandomErrors = {
    /**
     * 没有找到对应的一言
     */
    404: AtelinoInternalDtoResponse;
    /**
     * 数据库错误
     */
    500: AtelinoInternalDtoResponse;
};

export type GetHitokotoRandomError = GetHitokotoRandomErrors[keyof GetHitokotoRandomErrors];

export type GetHitokotoRandomResponses = {
    /**
     * 请求成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: AtelinoInternalDtoHitokotoResponse;
    };
};

export type GetHitokotoRandomResponse = GetHitokotoRandomResponses[keyof GetHitokotoRandomResponses];

export type CreateHitokotoData = {
    /**
     * 一言内容
     */
    body: AtelinoInternalDtoCreateHitokotoRequest;
    path?: never;
    query?: never;
    url: '/api/hitokoto';
};

export type CreateHitokotoErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 该一言已存在
     */
    409: AtelinoInternalDtoResponse;
    /**
     * 数据库错误
     */
    500: AtelinoInternalDtoResponse;
};

export type CreateHitokotoError = CreateHitokotoErrors[keyof CreateHitokotoErrors];

export type CreateHitokotoResponses = {
    /**
     * 添加成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: AtelinoInternalDtoHitokotoResponse;
    };
};

export type CreateHitokotoResponse = CreateHitokotoResponses[keyof CreateHitokotoResponses];

export type GetHitokotoListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页数
         */
        page?: number;
    };
    url: '/api/hitokoto/list';
};

export type GetHitokotoListErrors = {
    /**
     * 未授权
     */
    401: AtelinoInternalDtoResponse;
    /**
     * 数据库错误
     */
    500: AtelinoInternalDtoResponse;
};

export type GetHitokotoListError = GetHitokotoListErrors[keyof GetHitokotoListErrors];

export type GetHitokotoListResponses = {
    /**
     * 请求成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: Array<AtelinoInternalDtoHitokotoResponse>;
    };
};

export type GetHitokotoListResponse = GetHitokotoListResponses[keyof GetHitokotoListResponses];

export type DeleteHitokotoByIdData = {
    body?: never;
    path: {
        /**
         * 一言 ID
         */
        id: number;
    };
    query?: never;
    url: '/api/hitokoto/{id}';
};

export type DeleteHitokotoByIdErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 未授权
     */
    401: AtelinoInternalDtoResponse;
    /**
     * 没有找到对应的一言
     */
    404: AtelinoInternalDtoResponse;
    /**
     * 数据库错误
     */
    500: AtelinoInternalDtoResponse;
};

export type DeleteHitokotoByIdError = DeleteHitokotoByIdErrors[keyof DeleteHitokotoByIdErrors];

export type DeleteHitokotoByIdResponses = {
    /**
     * 删除成功
     */
    200: AtelinoInternalDtoResponse;
};

export type DeleteHitokotoByIdResponse = DeleteHitokotoByIdResponses[keyof DeleteHitokotoByIdResponses];

export type GetHitokotoByIdData = {
    body?: never;
    path: {
        /**
         * 一言 ID
         */
        id: number;
    };
    query?: never;
    url: '/api/hitokoto/{id}';
};

export type GetHitokotoByIdErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 未授权
     */
    401: AtelinoInternalDtoResponse;
    /**
     * 没有找到对应的一言
     */
    404: AtelinoInternalDtoResponse;
    /**
     * 数据库错误
     */
    500: AtelinoInternalDtoResponse;
};

export type GetHitokotoByIdError = GetHitokotoByIdErrors[keyof GetHitokotoByIdErrors];

export type GetHitokotoByIdResponses = {
    /**
     * 请求成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: AtelinoInternalDtoHitokotoResponse;
    };
};

export type GetHitokotoByIdResponse = GetHitokotoByIdResponses[keyof GetHitokotoByIdResponses];

export type GetUserListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页数，默认为1
         */
        page?: number;
    };
    url: '/api/user/list';
};

export type GetUserListErrors = {
    /**
     * 数据库错误
     */
    500: AtelinoInternalDtoResponse;
};

export type GetUserListError = GetUserListErrors[keyof GetUserListErrors];

export type GetUserListResponses = {
    /**
     * 请求成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: Array<AtelinoInternalDtoUserResponse>;
    };
};

export type GetUserListResponse = GetUserListResponses[keyof GetUserListResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        /**
         * 用户 ID
         */
        id: number;
    };
    query?: never;
    url: '/api/user/{id}';
};

export type GetUserByIdErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 未授权
     */
    401: AtelinoInternalDtoResponse;
    /**
     * 查询失败
     */
    500: AtelinoInternalDtoResponse;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
    /**
     * 请求成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: AtelinoInternalDtoUserResponse;
    };
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type LoginData = {
    /**
     * 登录请求体
     */
    body: AtelinoInternalDtoLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 用户名或密码错误
     */
    401: AtelinoInternalDtoResponse;
    /**
     * 登录失败
     */
    500: AtelinoInternalDtoResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * 登录成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: AtelinoInternalDtoTokenResponse;
    };
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutErrors = {
    /**
     * 未登录或登录状态无效
     */
    401: AtelinoInternalDtoResponse;
    /**
     * 登出失败
     */
    500: AtelinoInternalDtoResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * 登出成功
     */
    200: AtelinoInternalDtoResponse;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RefreshTokenData = {
    /**
     * 刷新令牌请求体
     */
    body: AtelinoInternalDtoRefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 令牌无效或已过期
     */
    401: AtelinoInternalDtoResponse;
    /**
     * 服务器内部错误
     */
    500: AtelinoInternalDtoResponse;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * 刷新成功
     */
    200: AtelinoInternalDtoResponse & {
        data?: AtelinoInternalDtoTokenResponse;
    };
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type RegisterData = {
    /**
     * 注册请求体
     */
    body: AtelinoInternalDtoRegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 该邮箱已注册
     */
    409: AtelinoInternalDtoResponse;
    /**
     * 注册失败
     */
    500: AtelinoInternalDtoResponse;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * 注册成功
     */
    200: AtelinoInternalDtoResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type SendVerificationCodeData = {
    /**
     * 邮箱地址
     */
    body: AtelinoInternalDtoSendVerificationCodeRequest;
    path?: never;
    query?: never;
    url: '/verify/send';
};

export type SendVerificationCodeErrors = {
    /**
     * 请求参数错误
     */
    400: AtelinoInternalDtoResponse;
    /**
     * 请求过于频繁，请稍后再试
     */
    429: AtelinoInternalDtoResponse;
    /**
     * 发送验证码失败
     */
    500: AtelinoInternalDtoResponse;
};

export type SendVerificationCodeError = SendVerificationCodeErrors[keyof SendVerificationCodeErrors];

export type SendVerificationCodeResponses = {
    /**
     * 发送成功
     */
    200: AtelinoInternalDtoResponse;
};

export type SendVerificationCodeResponse = SendVerificationCodeResponses[keyof SendVerificationCodeResponses];
